
name: Build on Ubuntu

on:
  pull_request:

jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: |
        ./mkn.sh
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn
        ./mkn clean build -dtOa -fPIC
